### ISSUE TITLE
Broken on Update Sketch 49.1

### ISSUE THREAD

**Issue by jonbraz0** [mamuso/sketch-truncate-textlines#5]
The plugin doesnt seem to work on the new Sketch update. it creates a new duplicate layer underneath the current layer...and doesn't add the ellipsis 
![screen shot 2018-03-26 at 12 28 53 pm](https://user-images.githubusercontent.com/26942919/37928404-938a5224-30f1-11e8-92c1-e2385cafe800.png)

**Comment by ghost** [comment]
I have same issue it duplicates new layer. :(

**Comment by mamuso** [comment]
I'll take a look at it this week

**Comment by johnymaker** [comment]
Could you correct the plugin for the new version of the Sketch?

**Comment by mamuso** [comment]
I need to put time aside to convert all my plugins to the new API. Will keep you posted with the progress, this is long overdue.

**Comment by mamuso** [comment]
@johnymaker, @extrayb @jonbraz0 this should be fixed in the version I just merged
